name: Test and Build

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

env:
  GO_VERSION: "1.19"

jobs:
  test:
    name: Test and Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Download dependencies
        run: go mod download

      - name: Build
        run: go build -v .

      - name: Run tests
        run: |
          if ls *_test.go >/dev/null 2>&1; then
            go test -v ./...
          else
            echo "No test files found, skipping tests"
          fi

      - name: Run go vet
        run: go vet ./...

      - name: Run go fmt check
        run: |
          if [ "$(gofmt -s -l . | wc -l)" -gt 0 ]; then
            echo "代码格式不正确，请运行: go fmt ./..."
            gofmt -s -l .
            exit 1
          fi

      - name: Test basic functionality
        run: |
          ./bddisk_uploader -init
          if [ -f "config.json" ]; then
            echo "✅ 基础功能测试通过"
          else
            echo "❌ 配置文件创建失败"
            exit 1
          fi
